var items = [];
items[ITEM_ACCURACY_RUBY_1] = {
	propsId: 1200,
	name: "Accuracy Ruby-I",
	comment: "Increases a Commander's accuracy by 13.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 26,
	gemLevel: 0,
	gemKindID: 1,
	gemValue: 13,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	aim: 13,
	gem1ID: 1,
	imageFileName: "Props1135"
};
items[ITEM_ACCURACY_RUBY_2] = {
	propsId: 1201,
	name: "Accuracy Ruby-II",
	comment: "Increases a Commander's accuracy by 26.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 1,
	gemValue: 26,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 26,
	gem1ID: 1,
	imageFileName: "Props1136"
};
items[ITEM_ACCURACY_RUBY_3] = {
	propsId: 1202,
	name: "Accuracy Ruby-III",
	comment: "Increases a Commander's accuracy by 39.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 1,
	gemValue: 39,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 39,
	gem1ID: 1,
	imageFileName: "Props1137"
};
items[ITEM_ACCURACY_RUBY_4] = {
	propsId: 1203,
	name: "Accuracy Ruby-IV",
	comment: "Increases a Commander's accuracy by 52.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 1,
	gemValue: 52,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 52,
	gem1ID: 1,
	imageFileName: "Props1138"
};
items[ITEM_ACCURACY_RUBY_5] = {
	propsId: 1204,
	name: "Accuracy Ruby-V",
	comment: "Increases a Commander's accuracy by 65.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 1,
	gemValue: 65,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 65,
	gem1ID: 1,
	imageFileName: "Props1139"
};
items[ITEM_ACCURACY_SAPPHIRE_1] = {
	propsId: 1205,
	name: "Accuracy Sapphire-I",
	comment: "Increases a Commander's accuracy by 9.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 27,
	gemLevel: 0,
	gemKindID: 1,
	gemValue: 9,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	aim: 9,
	gem1ID: 2,
	imageFileName: "Props1140"
};
items[ITEM_ACCURACY_SAPPHIRE_2] = {
	propsId: 1206,
	name: "Accuracy Sapphire-II",
	comment: "Increases a Commander's accuracy by 18.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 1,
	gemValue: 18,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 18,
	gem1ID: 2,
	imageFileName: "Props1141"
};
items[ITEM_ACCURACY_SAPPHIRE_3] = {
	propsId: 1207,
	name: "Accuracy Sapphire-III",
	comment: "Increases a Commander's accuracy by 27.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 1,
	gemValue: 27,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 27,
	gem1ID: 2,
	imageFileName: "Props1142"
};
items[ITEM_ACCURACY_SAPPHIRE_4] = {
	propsId: 1208,
	name: "Accuracy Sapphire-IV",
	comment: "Increases a Commander's accuracy by 36.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 1,
	gemValue: 36,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 36,
	gem1ID: 2,
	imageFileName: "Props1143"
};
items[ITEM_ACCURACY_SAPPHIRE_5] = {
	propsId: 1209,
	name: "Accuracy Sapphire-V",
	comment: "Increases a Commander's accuracy by 45.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 1,
	gemValue: 45,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 45,
	gem1ID: 2,
	imageFileName: "Props1144"
};
items[ITEM_ACCURACY_EMERALD_1] = {
	propsId: 1210,
	name: "Accuracy Emerald-I",
	comment: "Increases a Commander's accuracy by 5.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 28,
	gemLevel: 0,
	gemKindID: 1,
	gemValue: 5,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	aim: 5,
	gem1ID: 3,
	imageFileName: "Props1145"
};
items[ITEM_ACCURACY_EMERALD_2] = {
	propsId: 1211,
	name: "Accuracy Emerald-II",
	comment: "Increases a Commander's accuracy by 10.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 1,
	gemValue: 10,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 10,
	gem1ID: 3,
	imageFileName: "Props1146"
};
items[ITEM_ACCURACY_EMERALD_3] = {
	propsId: 1212,
	name: "Accuracy Emerald-III",
	comment: "Increases a Commander's accuracy by 15.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 1,
	gemValue: 15,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 15,
	gem1ID: 3,
	imageFileName: "Props1147"
};
items[ITEM_ACCURACY_EMERALD_4] = {
	propsId: 1213,
	name: "Accuracy Emerald-IV",
	comment: "Increases a Commander's accuracy by 20.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 1,
	gemValue: 20,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 20,
	gem1ID: 3,
	imageFileName: "Props1148"
};
items[ITEM_ACCURACY_EMERALD_5] = {
	propsId: 1214,
	name: "Accuracy Emerald-V",
	comment: "Increases a Commander's accuracy by 25.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 1,
	gemValue: 25,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 25,
	gem1ID: 3,
	imageFileName: "Props1149"
};
items[ITEM_DODGE_RUBY_1] = {
	propsId: 1215,
	name: "Dodge Ruby-I",
	comment: "Increases a Commander's dodge by 5.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 29,
	gemLevel: 0,
	gemKindID: 2,
	gemValue: 5,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	blench: 5,
	gem1ID: 1,
	imageFileName: "Props1060"
};
items[ITEM_DODGE_RUBY_2] = {
	propsId: 1216,
	name: "Dodge Ruby-II",
	comment: "Increases a Commander's dodge by 10.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 2,
	gemValue: 10,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 10,
	gem1ID: 1,
	imageFileName: "Props1061"
};
items[ITEM_DODGE_RUBY_3] = {
	propsId: 1217,
	name: "Dodge Ruby-III",
	comment: "Increases a Commander's dodge by 15.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 2,
	gemValue: 15,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 15,
	gem1ID: 1,
	imageFileName: "Props1062"
};
items[ITEM_DODGE_RUBY_4] = {
	propsId: 1218,
	name: "Dodge Ruby-IV",
	comment: "Increases a Commander's dodge by 20.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 2,
	gemValue: 20,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 20,
	gem1ID: 1,
	imageFileName: "Props1063"
};
items[ITEM_DODGE_RUBY_5] = {
	propsId: 1219,
	name: "Dodge Ruby-V",
	comment: "Increases a Commander's dodge by 25.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 2,
	gemValue: 25,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 25,
	gem1ID: 1,
	imageFileName: "Props1064"
};
items[ITEM_DODGE_SAPPHIRE_1] = {
	propsId: 1220,
	name: "Dodge Sapphire-I",
	comment: "Increases a Commander's dodge by 13.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 30,
	gemLevel: 0,
	gemKindID: 2,
	gemValue: 13,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	blench: 13,
	gem1ID: 2,
	imageFileName: "Props1065"
};
items[ITEM_DODGE_SAPPHIRE_2] = {
	propsId: 1221,
	name: "Dodge Sapphire-II",
	comment: "Increases a Commander's dodge by 26.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 2,
	gemValue: 26,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 26,
	gem1ID: 2,
	imageFileName: "Props1066"
};
items[ITEM_DODGE_SAPPHIRE_3] = {
	propsId: 1222,
	name: "Dodge Sapphire-III",
	comment: "Increases a Commander's dodge by 39.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 2,
	gemValue: 39,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 39,
	gem1ID: 2,
	imageFileName: "Props1067"
};
items[ITEM_DODGE_SAPPHIRE_4] = {
	propsId: 1223,
	name: "Dodge Sapphire-IV",
	comment: "Increases a Commander's dodge by 52.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 2,
	gemValue: 52,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 52,
	gem1ID: 2,
	imageFileName: "Props1068"
};
items[ITEM_DODGE_SAPPHIRE_5] = {
	propsId: 1224,
	name: "Dodge Sapphire-V",
	comment: "Increases a Commander's dodge by 65.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 2,
	gemValue: 65,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 65,
	gem1ID: 2,
	imageFileName: "Props1069"
};
items[ITEM_DODGE_EMERALD_1] = {
	propsId: 1225,
	name: "Dodge Emerald-I",
	comment: "Increases a Commander's dodge by 9.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 31,
	gemLevel: 0,
	gemKindID: 2,
	gemValue: 9,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	blench: 9,
	gem1ID: 3,
	imageFileName: "Props1070"
};
items[ITEM_DODGE_EMERALD_2] = {
	propsId: 1226,
	name: "Dodge Emerald-II",
	comment: "Increases a Commander's dodge by 18.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 2,
	gemValue: 18,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 18,
	gem1ID: 3,
	imageFileName: "Props1071"
};
items[ITEM_DODGE_EMERALD_3] = {
	propsId: 1227,
	name: "Dodge Emerald-III",
	comment: "Increases a Commander's dodge by 27.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 2,
	gemValue: 27,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 27,
	gem1ID: 3,
	imageFileName: "Props1072"
};
items[ITEM_DODGE_EMERALD_4] = {
	propsId: 1228,
	name: "Dodge Emerald-IV",
	comment: "Increases a Commander's dodge by 36.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 2,
	gemValue: 36,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 36,
	gem1ID: 3,
	imageFileName: "Props1073"
};
items[ITEM_DODGE_EMERALD_5] = {
	propsId: 1229,
	name: "Dodge Emerald-V",
	comment: "Increases a Commander's dodge by 45.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 2,
	gemValue: 45,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 45,
	gem1ID: 3,
	imageFileName: "Props1074"
};
items[ITEM_ELECTRON_RUBY_1] = {
	propsId: 1230,
	name: "Electron Ruby-I",
	comment: "Increases a Commander's electron by 9.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 32,
	gemLevel: 0,
	gemKindID: 3,
	gemValue: 9,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	electron: 9,
	gem1ID: 1,
	imageFileName: "Props1020"
};
items[ITEM_ELECTRON_RUBY_2] = {
	propsId: 1231,
	name: "Electron Ruby-II",
	comment: "Increases a Commander's electron by 18.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 3,
	gemValue: 18,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 18,
	gem1ID: 1,
	imageFileName: "Props1021"
};
items[ITEM_ELECTRON_RUBY_3] = {
	propsId: 1232,
	name: "Electron Ruby-III",
	comment: "Increases a Commander's electron by 27.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 3,
	gemValue: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 27,
	gem1ID: 1,
	imageFileName: "Props1022"
};
items[ITEM_ELECTRON_RUBY_4] = {
	propsId: 1233,
	name: "Electron Ruby-IV",
	comment: "Increases a Commander's electron by 36.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 3,
	gemValue: 36,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 36,
	gem1ID: 1,
	imageFileName: "Props1023"
};
items[ITEM_ELECTRON_RUBY_5] = {
	propsId: 1234,
	name: "Electron Ruby-V",
	comment: "Increases a Commander's electron by 45.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 3,
	gemValue: 45,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 45,
	gem1ID: 1,
	imageFileName: "Props1024"
};
items[ITEM_ELECTRON_SAPPHIRE_1] = {
	propsId: 1235,
	name: "Electron Sapphire-I",
	comment: "Increases a Commander's electron by 5.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 33,
	gemLevel: 0,
	gemKindID: 3,
	gemValue: 5,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	electron: 5,
	gem1ID: 2,
	imageFileName: "Props1025"
};
items[ITEM_ELECTRON_SAPPHIRE_2] = {
	propsId: 1236,
	name: "Electron Sapphire-II",
	comment: "Increases a Commander's electron by 10.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 3,
	gemValue: 10,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 10,
	gem1ID: 2,
	imageFileName: "Props1026"
};
items[ITEM_ELECTRON_SAPPHIRE_3] = {
	propsId: 1237,
	name: "Electron Sapphire-III",
	comment: "Increases a Commander's electron by 15.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 3,
	gemValue: 15,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 15,
	gem1ID: 2,
	imageFileName: "Props1027"
};
items[ITEM_ELECTRON_SAPPHIRE_4] = {
	propsId: 1238,
	name: "Electron Sapphire-IV",
	comment: "Increases a Commander's electron by 20.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 3,
	gemValue: 20,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 20,
	gem1ID: 2,
	imageFileName: "Props1028"
};
items[ITEM_ELECTRON_SAPPHIRE_5] = {
	propsId: 1239,
	name: "Electron Sapphire-V",
	comment: "Increases a Commander's electron by 25.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 3,
	gemValue: 25,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 25,
	gem1ID: 2,
	imageFileName: "Props1029"
};
items[ITEM_ELECTRON_EMERALD_1] = {
	propsId: 1240,
	name: "Electron Emerald-I",
	comment: "Increases a Commander's electron by 13.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 34,
	gemLevel: 0,
	gemKindID: 3,
	gemValue: 13,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	electron: 13,
	gem1ID: 3,
	imageFileName: "Props1030"
};
items[ITEM_ELECTRON_EMERALD_2] = {
	propsId: 1241,
	name: "Electron Emerald-II",
	comment: "Increases a Commander's electron by 26.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 3,
	gemValue: 26,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 26,
	gem1ID: 3,
	imageFileName: "Props1031"
};
items[ITEM_ELECTRON_EMERALD_3] = {
	propsId: 1242,
	name: "Electron Emerald-III",
	comment: "Increases a Commander's electron by 39.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 3,
	gemValue: 39,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 39,
	gem1ID: 3,
	imageFileName: "Props1032"
};
items[ITEM_ELECTRON_EMERALD_4] = {
	propsId: 1243,
	name: "Electron Emerald-IV",
	comment: "Increases a Commander's electron by 52.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 3,
	gemValue: 52,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 52,
	gem1ID: 3,
	imageFileName: "Props1033"
};
items[ITEM_ELECTRON_EMERALD_5] = {
	propsId: 1244,
	name: "Electron Emerald-V",
	comment: "Increases a Commander's electron by 65.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 3,
	gemValue: 65,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 65,
	gem1ID: 3,
	imageFileName: "Props1034"
};
items[ITEM_SPEED_RUBY_1] = {
	propsId: 1245,
	name: "Speed Ruby-I",
	comment: "Increases a Commander's speed by 9.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 35,
	gemLevel: 0,
	gemKindID: 4,
	gemValue: 9,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	priority: 9,
	gem1ID: 1,
	imageFileName: "Props1165"
};
items[ITEM_SPEED_RUBY_2] = {
	propsId: 1246,
	name: "Speed Ruby-II",
	comment: "Increases a Commander's speed by 18.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 4,
	gemValue: 18,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 18,
	gem1ID: 1,
	imageFileName: "Props1166"
};
items[ITEM_SPEED_RUBY_3] = {
	propsId: 1247,
	name: "Speed Ruby-III",
	comment: "Increases a Commander's speed by 27.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 4,
	gemValue: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 27,
	gem1ID: 1,
	imageFileName: "Props1167"
};
items[ITEM_SPEED_RUBY_4] = {
	propsId: 1248,
	name: "Speed Ruby-IV",
	comment: "Increases a Commander's speed by 36.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 4,
	gemValue: 36,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 36,
	gem1ID: 1,
	imageFileName: "Props1168"
};
items[ITEM_SPEED_RUBY_5] = {
	propsId: 1249,
	name: "Speed Ruby-V",
	comment: "Increases a Commander's speed by 45.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 4,
	gemValue: 45,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 45,
	gem1ID: 1,
	imageFileName: "Props1169"
};
items[ITEM_SPEED_SAPPHIRE_1] = {
	propsId: 1250,
	name: "Speed Sapphire-I",
	comment: "Increases a Commander's speed by 5.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 36,
	gemLevel: 0,
	gemKindID: 4,
	gemValue: 5,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	priority: 5,
	gem1ID: 2,
	imageFileName: "Props1170"
};
items[ITEM_SPEED_SAPPHIRE_2] = {
	propsId: 1251,
	name: "Speed Sapphire-II",
	comment: "Increases a Commander's speed by 10.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 4,
	gemValue: 10,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 10,
	gem1ID: 2,
	imageFileName: "Props1171"
};
items[ITEM_SPEED_SAPPHIRE_3] = {
	propsId: 1252,
	name: "Speed Sapphire-III",
	comment: "Increases a Commander's speed by 15.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 4,
	gemValue: 15,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 15,
	gem1ID: 2,
	imageFileName: "Props1172"
};
items[ITEM_SPEED_SAPPHIRE_4] = {
	propsId: 1253,
	name: "Speed Sapphire-IV",
	comment: "Increases a Commander's speed by 20.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 4,
	gemValue: 20,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 20,
	gem1ID: 2,
	imageFileName: "Props1173"
};
items[ITEM_SPEED_SAPPHIRE_5] = {
	propsId: 1254,
	name: "Speed Sapphire-V",
	comment: "Increases a Commander's speed by 25.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 4,
	gemValue: 25,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 25,
	gem1ID: 2,
	imageFileName: "Props1174"
};
items[ITEM_SPEED_EMERALD_1] = {
	propsId: 1255,
	name: "Speed Emerald-I",
	comment: "Increases a Commander's speed by 13.",
	suspendID: 0,
	challengeBox: 61,
	cash: 25,
	assortID: 3,
	orderID: 37,
	gemLevel: 0,
	gemKindID: 4,
	gemValue: 13,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	priority: 13,
	gem1ID: 3,
	imageFileName: "Props1175"
};
items[ITEM_SPEED_EMERALD_2] = {
	propsId: 1256,
	name: "Speed Emerald-II",
	comment: "Increases a Commander's speed by 26.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 4,
	gemValue: 26,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 26,
	gem1ID: 3,
	imageFileName: "Props1176"
};
items[ITEM_SPEED_EMERALD_3] = {
	propsId: 1257,
	name: "Speed Emerald-III",
	comment: "Increases a Commander's speed by 39.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 4,
	gemValue: 39,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 39,
	gem1ID: 3,
	imageFileName: "Props1177"
};
items[ITEM_SPEED_EMERALD_4] = {
	propsId: 1258,
	name: "Speed Emerald-IV",
	comment: "Increases a Commander's speed by 52.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 4,
	gemValue: 52,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 52,
	gem1ID: 3,
	imageFileName: "Props1178"
};
items[ITEM_SPEED_EMERALD_5] = {
	propsId: 1259,
	name: "Speed Emerald-V",
	comment: "Increases a Commander's speed by 65.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 4,
	gemValue: 65,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 65,
	gem1ID: 3,
	imageFileName: "Props1179"
};
items[ITEM_POWER_RUBY_1] = {
	propsId: 1260,
	name: "Power Ruby-I",
	comment: "Increases a ship's attack power by 0.7%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 38,
	gemLevel: 0,
	gemKindID: 5,
	gemValue: 70,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	assault: 70,
	gemID: 1,
	imageFileName: "Props1045"
};
items[ITEM_POWER_RUBY_2] = {
	propsId: 1261,
	name: "Power Ruby-II",
	comment: "Increases a ship's attack power by 1.3%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 5,
	gemValue: 130,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 130,
	gemID: 1,
	imageFileName: "Props1046"
};
items[ITEM_POWER_RUBY_3] = {
	propsId: 1262,
	name: "Power Ruby-III",
	comment: "Increases a ship's attack power by 2%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 5,
	gemValue: 2,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 200,
	gemID: 1,
	imageFileName: "Props1047"
};
items[ITEM_POWER_RUBY_4] = {
	propsId: 1263,
	name: "Power Ruby-IV",
	comment: "Increases a ship's attack power by 2.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 5,
	gemValue: 270,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 270,
	gemID: 1,
	imageFileName: "Props1048"
};
items[ITEM_POWER_RUBY_5] = {
	propsId: 1264,
	name: "Power Ruby-V",
	comment: "Increases a ship's attack power by 3.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 5,
	gemValue: 330,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 330,
	gemID: 1,
	imageFileName: "Props1049"
};
items[ITEM_POWER_SAPPHIRE_1] = {
	propsId: 1265,
	name: "Power Sapphire-I",
	comment: "Increases a ship's attack power by 0.4%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 39,
	gemLevel: 0,
	gemKindID: 5,
	gemValue: 40,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	assault: 40,
	gemID: 1,
	imageFileName: "Props1050"
};
items[ITEM_POWER_SAPPHIRE_2] = {
	propsId: 1266,
	name: "Power Sapphire-II",
	comment: "Increases a ship's attack power by 0.9%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 5,
	gemValue: 90,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	assault: 90,
	gemID: 1,
	imageFileName: "Props1051"
};
items[ITEM_POWER_SAPPHIRE_3] = {
	propsId: 1267,
	name: "Power Sapphire-III",
	comment: "Increases a ship's attack power by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 5,
	gemValue: 130,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	assault: 130,
	gemID: 1,
	imageFileName: "Props1052"
};
items[ITEM_POWER_SAPPHIRE_4] = {
	propsId: 1268,
	name: "Power Sapphire-IV",
	comment: "Increases a ship's attack power by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 5,
	gemValue: 170,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	assault: 170,
	gemID: 1,
	imageFileName: "Props1053"
};
items[ITEM_POWER_SAPPHIRE_5] = {
	propsId: 1269,
	name: "Power Sapphire-V",
	comment: "Increases a ship's attack power by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 5,
	gemValue: 220,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	assault: 220,
	gemID: 1,
	imageFileName: "Props1054"
};
items[ITEM_POWER_EMERALD_1] = {
	propsId: 1270,
	name: "Power Emerald-I",
	comment: "Increases a ship's attack power by 0.2%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 40,
	gemLevel: 0,
	gemKindID: 5,
	gemValue: 20,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	assault: 20,
	gemID: 1,
	imageFileName: "Props1055"
};
items[ITEM_POWER_EMERALD_2] = {
	propsId: 1271,
	name: "Power Emerald-II",
	comment: "Increases a ship's attack power by 0.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 5,
	gemValue: 50,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	assault: 50,
	gemID: 1,
	imageFileName: "Props1056"
};
items[ITEM_POWER_EMERALD_3] = {
	propsId: 1272,
	name: "Power Emerald-III",
	comment: "Increases a ship's attack power by 0.7%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 5,
	gemValue: 70,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	assault: 70,
	gemID: 1,
	imageFileName: "Props1057"
};
items[ITEM_POWER_EMERALD_4] = {
	propsId: 1273,
	name: "Power Emerald-IV",
	comment: "Increases a ship's attack power by 0.9%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 5,
	gemValue: 90,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	assault: 90,
	gemID: 1,
	imageFileName: "Props1058"
};
items[ITEM_POWER_EMERALD_5] = {
	propsId: 1274,
	name: "Power Emerald-V",
	comment: "Increases a ship's attack power by 1.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 5,
	gemValue: 120,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	assault: 120,
	gemID: 1,
	imageFileName: "Props1059"
};
items[ITEM_STRUCTURE_RUBY_1] = {
	propsId: 1275,
	name: "Structure Ruby-I",
	comment: "Increases a ship's structure by 0.2%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 41,
	gemLevel: 0,
	gemKindID: 6,
	gemValue: 20,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	endure: 20,
	gemID: 2,
	imageFileName: "Props1115"
};
items[ITEM_STRUCTURE_RUBY_2] = {
	propsId: 1276,
	name: "Structure Ruby-II",
	comment: "Increases a ship's structure by 0.3%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 6,
	gemValue: 30,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	endure: 30,
	gemID: 2,
	imageFileName: "Props1116"
};
items[ITEM_STRUCTURE_RUBY_3] = {
	propsId: 1277,
	name: "Structure Ruby-III",
	comment: "Increases a ship's structure by 0.5%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 6,
	gemValue: 50,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	endure: 50,
	gemID: 2,
	imageFileName: "Props1117"
};
items[ITEM_STRUCTURE_RUBY_4] = {
	propsId: 1278,
	name: "Structure Ruby-IV",
	comment: "Increases a ship's structure by 0.6%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 6,
	gemValue: 60,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	endure: 60,
	gemID: 2,
	imageFileName: "Props1118"
};
items[ITEM_STRUCTURE_RUBY_5] = {
	propsId: 1279,
	name: "Structure Ruby-V",
	comment: "Increases a ship's structure by 0.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 6,
	gemValue: 80,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	endure: 80,
	gemID: 2,
	imageFileName: "Props1119"
};
items[ITEM_STRUCTURE_SAPPHIRE_1] = {
	propsId: 1280,
	name: "Structure Sapphire-I",
	comment: "Increases a ship's structure by 0.4%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 42,
	gemLevel: 0,
	gemKindID: 6,
	gemValue: 40,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	endure: 40,
	gemID: 2,
	imageFileName: "Props1120"
};
items[ITEM_STRUCTURE_SAPPHIRE_2] = {
	propsId: 1281,
	name: "Structure Sapphire-II",
	comment: "Increases a ship's structure by 0.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 6,
	gemValue: 80,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 80,
	gemID: 2,
	imageFileName: "Props1121"
};
items[ITEM_STRUCTURE_SAPPHIRE_3] = {
	propsId: 1282,
	name: "Structure Sapphire-III",
	comment: "Increases a ship's structure by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 6,
	gemValue: 130,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 130,
	gemID: 2,
	imageFileName: "Props1122"
};
items[ITEM_STRUCTURE_SAPPHIRE_4] = {
	propsId: 1283,
	name: "Structure Sapphire-IV",
	comment: "Increases a ship's structure by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 6,
	gemValue: 170,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 170,
	gemID: 2,
	imageFileName: "Props1123"
};
items[ITEM_STRUCTURE_SAPPHIRE_5] = {
	propsId: 1284,
	name: "Structure Sapphire-V",
	comment: "Increases a ship's structure by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 6,
	gemValue: 220,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 220,
	gemID: 2,
	imageFileName: "Props1124"
};
items[ITEM_STRUCTURE_EMERALD_1] = {
	propsId: 1285,
	name: "Structure Emerald-I",
	comment: "Increases a ship's structure by 0.3%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 43,
	gemLevel: 0,
	gemKindID: 6,
	gemValue: 30,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	endure: 30,
	gemID: 2,
	imageFileName: "Props1125"
};
items[ITEM_STRUCTURE_EMERALD_2] = {
	propsId: 1286,
	name: "Structure Emerald-II",
	comment: "Increases a ship's structure by 0.6%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 6,
	gemValue: 60,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	endure: 60,
	gemID: 2,
	imageFileName: "Props1126"
};
items[ITEM_STRUCTURE_EMERALD_3] = {
	propsId: 1287,
	name: "Structure Emerald-III",
	comment: "Increases a ship's structure by 0.9%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 6,
	gemValue: 90,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	endure: 90,
	gemID: 2,
	imageFileName: "Props1127"
};
items[ITEM_STRUCTURE_EMERALD_4] = {
	propsId: 1288,
	name: "Structure Emerald-IV",
	comment: "Increases a ship's structure by 1.3%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 6,
	gemValue: 130,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	endure: 130,
	gemID: 2,
	imageFileName: "Props1128"
};
items[ITEM_STRUCTURE_EMERALD_5] = {
	propsId: 1289,
	name: "Structure Emerald-V",
	comment: "Increases a ship's structure by 1.5%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 6,
	gemValue: 150,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	endure: 150,
	gemID: 2,
	imageFileName: "Props1129"
};
items[ITEM_SHIELD_RUBY_1] = {
	propsId: 1290,
	name: "Shield Ruby-I",
	comment: "Increases a ship's shields by 0.2%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 44,
	gemLevel: 0,
	gemKindID: 7,
	gemValue: 20,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	shield: 20,
	gemID: 3,
	imageFileName: "Props1075"
};
items[ITEM_SHIELD_RUBY_2] = {
	propsId: 1291,
	name: "Shield Ruby-II",
	comment: "Increases a ship's shields by 0.4%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 7,
	gemValue: 40,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	shield: 40,
	gemID: 3,
	imageFileName: "Props1076"
};
items[ITEM_SHIELD_RUBY_3] = {
	propsId: 1292,
	name: "Shield Ruby-III",
	comment: "Increases a ship's shields by 0.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 7,
	gemValue: 60,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	shield: 60,
	gemID: 3,
	imageFileName: "Props1077"
};
items[ITEM_SHIELD_RUBY_4] = {
	propsId: 1293,
	name: "Shield Ruby-IV",
	comment: "Increases a ship's shields by 0.8%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 7,
	gemValue: 80,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	shield: 80,
	gemID: 3,
	imageFileName: "Props1078"
};
items[ITEM_SHIELD_RUBY_5] = {
	propsId: 1294,
	name: "Shield Ruby-V",
	comment: "Increases a ship's shields by 1%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 7,
	gemValue: 1,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	shield: 100,
	gemID: 3,
	imageFileName: "Props1079"
};
items[ITEM_SHIELD_SAPPHIRE_1] = {
	propsId: 1295,
	name: "Shield Sapphire-I",
	comment: "Increases a ship's shields by 0.5%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 45,
	gemLevel: 0,
	gemKindID: 7,
	gemValue: 50,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	shield: 50,
	gemID: 3,
	imageFileName: "Props1080"
};
items[ITEM_SHIELD_SAPPHIRE_2] = {
	propsId: 1296,
	name: "Shield Sapphire-II",
	comment: "Increases a ship's shields by 1%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 7,
	gemValue: 1,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	shield: 100,
	gemID: 3,
	imageFileName: "Props1081"
};
items[ITEM_SHIELD_SAPPHIRE_3] = {
	propsId: 1297,
	name: "Shield Sapphire-III",
	comment: "Increases a ship's shields by 1.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 7,
	gemValue: 160,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	shield: 160,
	gemID: 3,
	imageFileName: "Props1082"
};
items[ITEM_SHIELD_SAPPHIRE_4] = {
	propsId: 1298,
	name: "Shield Sapphire-IV",
	comment: "Increases a ship's shields by 2.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 7,
	gemValue: 210,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	shield: 210,
	gemID: 3,
	imageFileName: "Props1083"
};
items[ITEM_SHIELD_SAPPHIRE_5] = {
	propsId: 1299,
	name: "Shield Sapphire-V",
	comment: "Increases a ship's shields by 2.7%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 7,
	gemValue: 270,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	shield: 270,
	gemID: 3,
	imageFileName: "Props1084"
};
items[ITEM_SHIELD_EMERALD_1] = {
	propsId: 1300,
	name: "Shield Emerald-I",
	comment: "Increases a ship's shields by 0.4%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 46,
	gemLevel: 0,
	gemKindID: 7,
	gemValue: 40,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	shield: 40,
	gemID: 3,
	imageFileName: "Props1085"
};
items[ITEM_SHIELD_EMERALD_2] = {
	propsId: 1301,
	name: "Shield Emerald-II",
	comment: "Increases a ship's shields by 0.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 7,
	gemValue: 80,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	shield: 80,
	gemID: 3,
	imageFileName: "Props1086"
};
items[ITEM_SHIELD_EMERALD_3] = {
	propsId: 1302,
	name: "Shield Emerald-III",
	comment: "Increases a ship's shields by 1.2%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 7,
	gemValue: 120,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	shield: 120,
	gemID: 3,
	imageFileName: "Props1087"
};
items[ITEM_SHIELD_EMERALD_4] = {
	propsId: 1303,
	name: "Shield Emerald-IV",
	comment: "Increases a ship's shields by 1.6%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 7,
	gemValue: 160,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	shield: 160,
	gemID: 3,
	imageFileName: "Props1088"
};
items[ITEM_SHIELD_EMERALD_5] = {
	propsId: 1304,
	name: "Shield Emerald-V",
	comment: "Increases a ship's shields by 2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 7,
	gemValue: 2,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	shield: 200,
	gemID: 3,
	imageFileName: "Props1089"
};
items[ITEM_MALICE_RUBY_1] = {
	propsId: 1305,
	name: "Malice Ruby-I",
	comment: "Increases critical strike damage by 2.2%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 47,
	gemLevel: 0,
	gemKindID: 8,
	gemValue: 220,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	blastHurt: 220,
	gemID: 4,
	imageFileName: "Props1195"
};
items[ITEM_MALICE_RUBY_2] = {
	propsId: 1306,
	name: "Malice Ruby-II",
	comment: "Increases critical strike damage by 4.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 8,
	gemValue: 450,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blastHurt: 450,
	gemID: 4,
	imageFileName: "Props1196"
};
items[ITEM_MALICE_RUBY_3] = {
	propsId: 1307,
	name: "Malice Ruby-III",
	comment: "Increases critical strike damage by 6.7%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 8,
	gemValue: 670,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blastHurt: 670,
	gemID: 4,
	imageFileName: "Props1197"
};
items[ITEM_MALICE_RUBY_4] = {
	propsId: 1308,
	name: "Malice Ruby-IV",
	comment: "Increases critical strike damage by 9%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 8,
	gemValue: 9,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blastHurt: 900,
	gemID: 4,
	imageFileName: "Props1198"
};
items[ITEM_MALICE_RUBY_5] = {
	propsId: 1309,
	name: "Malice Ruby-V",
	comment: "Increases critical strike damage by 11.1%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 8,
	gemValue: 1110,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blastHurt: 1110,
	gemID: 4,
	imageFileName: "Props1199"
};
items[ITEM_MALICE_SAPPHIRE_1] = {
	propsId: 1310,
	name: "Malice Sapphire-I",
	comment: "Increases critical strike damage by 1.4%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 48,
	gemLevel: 0,
	gemKindID: 8,
	gemValue: 140,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	blastHurt: 140,
	gemID: 4,
	imageFileName: "Props1200"
};
items[ITEM_MALICE_SAPPHIRE_2] = {
	propsId: 1311,
	name: "Malice Sapphire-II",
	comment: "Increases critical strike damage by 2.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 8,
	gemValue: 280,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blastHurt: 280,
	gemID: 4,
	imageFileName: "Props1201"
};
items[ITEM_MALICE_SAPPHIRE_3] = {
	propsId: 1312,
	name: "Malice Sapphire-III",
	comment: "Increases critical strike damage by 4.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 8,
	gemValue: 430,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blastHurt: 430,
	gemID: 4,
	imageFileName: "Props1202"
};
items[ITEM_MALICE_SAPPHIRE_4] = {
	propsId: 1313,
	name: "Malice Sapphire-IV",
	comment: "Increases critical strike damage by 5.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 8,
	gemValue: 570,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blastHurt: 570,
	gemID: 4,
	imageFileName: "Props1203"
};
items[ITEM_MALICE_SAPPHIRE_5] = {
	propsId: 1314,
	name: "Malice Sapphire-V",
	comment: "Increases critical strike damage by 7.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 8,
	gemValue: 720,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blastHurt: 720,
	gemID: 4,
	imageFileName: "Props1204"
};
items[ITEM_MALICE_EMERALD_1] = {
	propsId: 1315,
	name: "Malice Emerald-I",
	comment: "Increases critical strike damage by 0.7%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 49,
	gemLevel: 0,
	gemKindID: 8,
	gemValue: 70,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	blastHurt: 70,
	gemID: 4,
	imageFileName: "Props1205"
};
items[ITEM_MALICE_EMERALD_2] = {
	propsId: 1316,
	name: "Malice Emerald-II",
	comment: "Increases critical strike damage by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 8,
	gemValue: 150,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 150,
	gemID: 4,
	imageFileName: "Props1206"
};
items[ITEM_MALICE_EMERALD_3] = {
	propsId: 1317,
	name: "Malice Emerald-III",
	comment: "Increases critical strike damage by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 8,
	gemValue: 230,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 230,
	gemID: 4,
	imageFileName: "Props1207"
};
items[ITEM_MALICE_EMERALD_4] = {
	propsId: 1318,
	name: "Malice Emerald-IV",
	comment: "Increases critical strike damage by 3%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 8,
	gemValue: 3,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 300,
	gemID: 4,
	imageFileName: "Props1208"
};
items[ITEM_MALICE_EMERALD_5] = {
	propsId: 1319,
	name: "Malice Emerald-V",
	comment: "Increases critical strike damage by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 8,
	gemValue: 380,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 380,
	gemID: 4,
	imageFileName: "Props1209"
};
items[ITEM_FEROCITY_RUBY_1] = {
	propsId: 1320,
	name: "Ferocity Ruby-I",
	comment: "Increases a ship's critical hit rate by 0.4%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 50,
	gemLevel: 0,
	gemKindID: 9,
	gemValue: 40,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	blast: 40,
	gemID: 5,
	imageFileName: "Props1000"
};
items[ITEM_FEROCITY_RUBY_2] = {
	propsId: 1321,
	name: "Ferocity Ruby-II",
	comment: "Increases a ship's critical hit rate by 0.9%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 9,
	gemValue: 90,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blast: 90,
	gemID: 5,
	imageFileName: "Props1001"
};
items[ITEM_FEROCITY_RUBY_3] = {
	propsId: 1322,
	name: "Ferocity Ruby-III",
	comment: "Increases a ship's critical hit rate by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 9,
	gemValue: 130,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blast: 130,
	gemID: 5,
	imageFileName: "Props1002"
};
items[ITEM_FEROCITY_RUBY_4] = {
	propsId: 1323,
	name: "Ferocity Ruby-IV",
	comment: "Increases a ship's critical hit rate by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 9,
	gemValue: 170,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blast: 170,
	gemID: 5,
	imageFileName: "Props1003"
};
items[ITEM_FEROCITY_RUBY_5] = {
	propsId: 1324,
	name: "Ferocity Ruby-V",
	comment: "Increases a ship's critical hit rate by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 9,
	gemValue: 220,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blast: 220,
	gemID: 5,
	imageFileName: "Props1004"
};
items[ITEM_FEROCITY_SAPPHIRE_1] = {
	propsId: 1325,
	name: "Ferocity Sapphire-I",
	comment: "Increases a ship's critical hit rate by 0.2%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 51,
	gemLevel: 0,
	gemKindID: 9,
	gemValue: 20,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	blast: 20,
	gemID: 5,
	imageFileName: "Props1010"
};
items[ITEM_FEROCITY_SAPPHIRE_2] = {
	propsId: 1326,
	name: "Ferocity Sapphire-II",
	comment: "Increases a ship's critical hit rate by 0.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 9,
	gemValue: 50,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blast: 50,
	gemID: 5,
	imageFileName: "Props1011"
};
items[ITEM_FEROCITY_SAPPHIRE_3] = {
	propsId: 1327,
	name: "Ferocity Sapphire-III",
	comment: "Increases a ship's critical hit rate by 0.7%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 9,
	gemValue: 70,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blast: 70,
	gemID: 5,
	imageFileName: "Props1012"
};
items[ITEM_FEROCITY_SAPPHIRE_4] = {
	propsId: 1328,
	name: "Ferocity Sapphire-IV",
	comment: "Increases a ship's critical hit rate by 0.9%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 9,
	gemValue: 90,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blast: 90,
	gemID: 5,
	imageFileName: "Props1013"
};
items[ITEM_FEROCITY_SAPPHIRE_5] = {
	propsId: 1329,
	name: "Ferocity Sapphire-V",
	comment: "Increases a ship's critical hit rate by 1.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 9,
	gemValue: 120,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blast: 120,
	gemID: 5,
	imageFileName: "Props1014"
};
items[ITEM_FEROCITY_EMERALD_1] = {
	propsId: 1330,
	name: "Ferocity Emerald-I",
	comment: "Increases a ship's critical hit rate by 0.7%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 52,
	gemLevel: 0,
	gemKindID: 9,
	gemValue: 70,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	blast: 70,
	gemID: 5,
	imageFileName: "Props1005"
};
items[ITEM_FEROCITY_EMERALD_2] = {
	propsId: 1331,
	name: "Ferocity Emerald-II",
	comment: "Increases a ship's critical hit rate by 1.3%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 9,
	gemValue: 130,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blast: 130,
	gemID: 5,
	imageFileName: "Props1006"
};
items[ITEM_FEROCITY_EMERALD_3] = {
	propsId: 1332,
	name: "Ferocity Emerald-III",
	comment: "Increases a ship's critical hit rate by 2%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 9,
	gemValue: 2,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blast: 200,
	gemID: 5,
	imageFileName: "Props1007"
};
items[ITEM_FEROCITY_EMERALD_4] = {
	propsId: 1333,
	name: "Ferocity Emerald-IV",
	comment: "Increases a ship's critical hit rate by 2.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 9,
	gemValue: 270,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blast: 270,
	gemID: 5,
	imageFileName: "Props1008"
};
items[ITEM_FEROCITY_EMERALD_5] = {
	propsId: 1334,
	name: "Ferocity Emerald-V",
	comment: "Increases a ship's critical hit rate by 3.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 9,
	gemValue: 330,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blast: 330,
	gemID: 5,
	imageFileName: "Props1009"
};
items[ITEM_CHRONO_RUBY_1] = {
	propsId: 1335,
	name: "Chrono Ruby-I",
	comment: "Increases a ship's chance to double-hit by 0.6%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 53,
	gemLevel: 0,
	gemKindID: 10,
	gemValue: 60,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	doubleHit: 60,
	gemID: 6,
	imageFileName: "Props1150"
};
items[ITEM_CHRONO_RUBY_2] = {
	propsId: 1336,
	name: "Chrono Ruby-II",
	comment: "Increases a ship's chance to double-hit by 1.3%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 10,
	gemValue: 130,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	doubleHit: 130,
	gemID: 6,
	imageFileName: "Props1151"
};
items[ITEM_CHRONO_RUBY_3] = {
	propsId: 1337,
	name: "Chrono Ruby-III",
	comment: "Increases a ship's chance to double-hit by 1.9%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 10,
	gemValue: 190,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	doubleHit: 190,
	gemID: 6,
	imageFileName: "Props1152"
};
items[ITEM_CHRONO_RUBY_4] = {
	propsId: 1338,
	name: "Chrono Ruby-IV",
	comment: "Increases a ship's chance to double-hit by 2.5%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 10,
	gemValue: 250,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	doubleHit: 250,
	gemID: 6,
	imageFileName: "Props1153"
};
items[ITEM_CHRONO_RUBY_5] = {
	propsId: 1339,
	name: "Chrono Ruby-V",
	comment: "Increases a ship's chance to double-hit by 3.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 10,
	gemValue: 320,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	doubleHit: 320,
	gemID: 6,
	imageFileName: "Props1154"
};
items[ITEM_CHRONO_SAPPHIRE_1] = {
	propsId: 1340,
	name: "Chrono Sapphire-I",
	comment: "Increases a ship's chance to double-hit by 0.3%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 54,
	gemLevel: 0,
	gemKindID: 10,
	gemValue: 30,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	doubleHit: 30,
	gemID: 6,
	imageFileName: "Props1155"
};
items[ITEM_CHRONO_SAPPHIRE_2] = {
	propsId: 1341,
	name: "Chrono Sapphire-II",
	comment: "Increases a ship's chance to double-hit by 0.6%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 10,
	gemValue: 60,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	doubleHit: 60,
	gemID: 6,
	imageFileName: "Props1156"
};
items[ITEM_CHRONO_SAPPHIRE_3] = {
	propsId: 1342,
	name: "Chrono Sapphire-III",
	comment: "Increases a ship's chance to double-hit by 0.9%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 10,
	gemValue: 90,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	doubleHit: 90,
	gemID: 6,
	imageFileName: "Props1157"
};
items[ITEM_CHRONO_SAPPHIRE_4] = {
	propsId: 1343,
	name: "Chrono Sapphire-IV",
	comment: "Increases a ship's chance to double-hit by 1.2%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 10,
	gemValue: 120,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	doubleHit: 120,
	gemID: 6,
	imageFileName: "Props1158"
};
items[ITEM_CHRONO_SAPPHIRE_5] = {
	propsId: 1344,
	name: "Chrono Sapphire-V",
	comment: "Increases a ship's chance to double-hit by 1.5%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 10,
	gemValue: 150,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	doubleHit: 150,
	gemID: 6,
	imageFileName: "Props1159"
};
items[ITEM_CHRONO_EMERALD_1] = {
	propsId: 1345,
	name: "Chrono Emerald-I",
	comment: "Increases a ship's chance to double-hit by 0.9%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 55,
	gemLevel: 0,
	gemKindID: 10,
	gemValue: 90,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	doubleHit: 90,
	gemID: 6,
	imageFileName: "Props1160"
};
items[ITEM_CHRONO_EMERALD_2] = {
	propsId: 1346,
	name: "Chrono Emerald-II",
	comment: "Increases a ship's chance to double-hit by 1.7%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 10,
	gemValue: 170,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	doubleHit: 170,
	gemID: 6,
	imageFileName: "Props1161"
};
items[ITEM_CHRONO_EMERALD_3] = {
	propsId: 1347,
	name: "Chrono Emerald-III",
	comment: "Increases a ship's chance to double-hit by 2.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 10,
	gemValue: 260,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	doubleHit: 260,
	gemID: 6,
	imageFileName: "Props1162"
};
items[ITEM_CHRONO_EMERALD_4] = {
	propsId: 1348,
	name: "Chrono Emerald-IV",
	comment: "Increases a ship's chance to double-hit by 3.4%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 10,
	gemValue: 340,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	doubleHit: 340,
	gemID: 6,
	imageFileName: "Props1163"
};
items[ITEM_CHRONO_EMERALD_5] = {
	propsId: 1349,
	name: "Chrono Emerald-V",
	comment: "Increases a ship's chance to double-hit by 4.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 10,
	gemValue: 430,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	doubleHit: 430,
	gemID: 6,
	imageFileName: "Props1164"
};
items[ITEM_REGEN_RUBY_1] = {
	propsId: 1350,
	name: "Regen Ruby-I",
	comment: "Increases a ship's shield regeneration rate by 0.3%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 56,
	gemLevel: 0,
	gemKindID: 11,
	gemValue: 30,
	gemColor: 1,
	eolith: 1,
	red: 1,
	//diamond: 1,
	repairShield: 30,
	gemID: 7,
	imageFileName: "Props1095"
};
items[ITEM_REGEN_RUBY_2] = {
	propsId: 1351,
	name: "Regen Ruby-II",
	comment: "Increases a ship's shield regeneration rate by 0.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 11,
	gemValue: 50,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	repairShield: 50,
	gemID: 7,
	imageFileName: "Props1096"
};
items[ITEM_REGEN_RUBY_3] = {
	propsId: 1352,
	name: "Regen Ruby-III",
	comment: "Increases a ship's shield regeneration rate by 0.8%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 11,
	gemValue: 80,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	repairShield: 80,
	gemID: 7,
	imageFileName: "Props1097"
};
items[ITEM_REGEN_RUBY_4] = {
	propsId: 1353,
	name: "Regen Ruby-IV",
	comment: "Increases a ship's shield regeneration rate by 1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 11,
	gemValue: 1,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	repairShield: 100,
	gemID: 7,
	imageFileName: "Props1098"
};
items[ITEM_REGEN_RUBY_5] = {
	propsId: 1354,
	name: "Regen Ruby-V",
	comment: "Increases a ship's shield regeneration rate by 1.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 11,
	gemValue: 130,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	repairShield: 130,
	gemID: 7,
	imageFileName: "Props1099"
};
items[ITEM_REGEN_SAPPHIRE_1] = {
	propsId: 1355,
	name: "Regen Sapphire-I",
	comment: "Increases a ship's shield regeneration rate by 0.8%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 57,
	gemLevel: 0,
	gemKindID: 11,
	gemValue: 80,
	gemColor: 2,
	eolith: 1,
	blue: 1,
	//diamond: 1,
	repairShield: 80,
	gemID: 7,
	imageFileName: "Props1100"
};
items[ITEM_REGEN_SAPPHIRE_2] = {
	propsId: 1356,
	name: "Regen Sapphire-II",
	comment: "Increases a ship's shield regeneration rate by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 11,
	gemValue: 150,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	repairShield: 150,
	gemID: 7,
	imageFileName: "Props1101"
};
items[ITEM_REGEN_SAPPHIRE_3] = {
	propsId: 1357,
	name: "Regen Sapphire-III",
	comment: "Increases a ship's shield regeneration rate by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 11,
	gemValue: 230,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	repairShield: 230,
	gemID: 7,
	imageFileName: "Props1102"
};
items[ITEM_REGEN_SAPPHIRE_4] = {
	propsId: 1358,
	name: "Regen Sapphire-IV",
	comment: "Increases a ship's shield regeneration rate by 3.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 11,
	gemValue: 310,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	repairShield: 310,
	gemID: 7,
	imageFileName: "Props1103"
};
items[ITEM_REGEN_SAPPHIRE_5] = {
	propsId: 1359,
	name: "Regen Sapphire-V",
	comment: "Increases a ship's shield regeneration rate by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 11,
	gemValue: 380,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	repairShield: 380,
	gemID: 7,
	imageFileName: "Props1104"
};
items[ITEM_REGEN_EMERALD_1] = {
	propsId: 1360,
	name: "Regen Emerald-I",
	comment: "Increases a ship's shield regeneration rate by 0.5%.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 58,
	gemLevel: 0,
	gemKindID: 11,
	gemValue: 50,
	gemColor: 3,
	eolith: 1,
	green: 1,
	//diamond: 1,
	repairShield: 50,
	gemID: 7,
	imageFileName: "Props1105"
};
items[ITEM_REGEN_EMERALD_2] = {
	propsId: 1361,
	name: "Regen Emerald-II",
	comment: "Increases a ship's shield regeneration rate by 1%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 11,
	gemValue: 1,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	repairShield: 100,
	gemID: 7,
	imageFileName: "Props1106"
};
items[ITEM_REGEN_EMERALD_3] = {
	propsId: 1362,
	name: "Regen Emerald-III",
	comment: "Increases a ship's shield regeneration rate by 1.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 11,
	gemValue: 160,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	repairShield: 160,
	gemID: 7,
	imageFileName: "Props1107"
};
items[ITEM_REGEN_EMERALD_4] = {
	propsId: 1363,
	name: "Regen Emerald-IV",
	comment: "Increases a ship's shield regeneration rate by 2.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 11,
	gemValue: 210,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	repairShield: 210,
	gemID: 7,
	imageFileName: "Props1108"
};
items[ITEM_REGEN_EMERALD_5] = {
	propsId: 1364,
	name: "Regen Emerald-V",
	comment: "Increases a ship's shield regeneration rate by 2.7%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 11,
	gemValue: 270,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	repairShield: 270,
	gemID: 7,
	imageFileName: "Props1109"
};
items[ITEM_EXP_DIAMOND_1] = {
	propsId: 1365,
	name: "EXP Diamond-I",
	comment: "Increases EXP earned by a commander by 10%",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 59,
	gemLevel: 0,
	gemKindID: 12,
	gemValue: 10,
	gemColor: 4,
	diamond: 1,
	exp: 10,
	imageFileName: "Props1130"
};
items[ITEM_EXP_DIAMOND_2] = {
	propsId: 1366,
	name: "EXP Diamond-II",
	comment: "Increases EXP earned by a commander by 20%",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 12,
	gemValue: 20,
	gemColor: 4,
	diamond: 1,
	exp: 20,
	imageFileName: "Props1131"
};
items[ITEM_EXP_DIAMOND_3] = {
	propsId: 1367,
	name: "EXP Diamond-III",
	comment: "Increases EXP earned by a commander by 30%",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 12,
	gemValue: 30,
	gemColor: 4,
	diamond: 1,
	exp: 30,
	imageFileName: "Props1132"
};
items[ITEM_EXP_DIAMOND_4] = {
	propsId: 1368,
	name: "EXP Diamond-IV",
	comment: "Increases EXP earned by a commander by 40%",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 12,
	gemValue: 40,
	gemColor: 4,
	diamond: 1,
	exp: 40,
	imageFileName: "Props1133"
};
items[ITEM_EXP_DIAMOND_5] = {
	propsId: 1369,
	name: "EXP Diamond-V",
	comment: "Increases EXP earned by a commander by 50%",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 12,
	gemValue: 50,
	gemColor: 4,
	diamond: 1,
	exp: 50,
	imageFileName: "Props1134"
};
items[ITEM_BALLISTIC_DIAMOND_1] = {
	propsId: 1370,
	name: "Ballistic Diamond-I",
	comment: "Ballistic Weapon Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 60,
	gemLevel: 0,
	gemKindID: 13,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	ballistic: "D",
	imageFileName: "Props1015"
};
items[ITEM_BALLISTIC_DIAMOND_2] = {
	propsId: 1371,
	name: "Ballistic Diamond-II",
	comment: "Ballistic Weapon Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 13,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	ballistic: "C",
	imageFileName: "Props1016"
};
items[ITEM_BALLISTIC_DIAMOND_3] = {
	propsId: 1372,
	name: "Ballistic Diamond-III",
	comment: "Ballistic Weapon Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 13,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	ballistic: "B",
	imageFileName: "Props1017"
};
items[ITEM_BALLISTIC_DIAMOND_4] = {
	propsId: 1373,
	name: "Ballistic Diamond-IV",
	comment: "Ballistic Weapon Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 13,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	ballistic: "A",
	imageFileName: "Props1018"
};
items[ITEM_BALLISTIC_DIAMOND_5] = {
	propsId: 1374,
	name: "Ballistic Diamond-V",
	comment: "Ballistic Weapon Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 13,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	ballistic: "S",
	imageFileName: "Props1019"
};
items[ITEM_DIRECTIONAL_DIAMOND_1] = {
	propsId: 1375,
	name: "Directional Diamond-I",
	comment: "Directional Weapon Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 61,
	gemLevel: 0,
	gemKindID: 14,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	directional: "D",
	imageFileName: "Props1035"
};
items[ITEM_DIRECTIONAL_DIAMOND_2] = {
	propsId: 1376,
	name: "Directional Diamond-II",
	comment: "Directional Weapon Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 14,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	directional: "C",
	imageFileName: "Props1036"
};
items[ITEM_DIRECTIONAL_DIAMOND_3] = {
	propsId: 1377,
	name: "Directional Diamond-III",
	comment: "Directional Weapon Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 14,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	directional: "B",
	imageFileName: "Props1037"
};
items[ITEM_DIRECTIONAL_DIAMOND_4] = {
	propsId: 1378,
	name: "Directional Diamond-IV",
	comment: "Directional Weapon Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 14,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	directional: "A",
	imageFileName: "Props1038"
};
items[ITEM_DIRECTIONAL_DIAMOND_5] = {
	propsId: 1379,
	name: "Directional Diamond-V",
	comment: "Directional Weapon Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 14,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	directional: "S",
	imageFileName: "Props1039"
};
items[ITEM_MISSILE_DIAMOND_1] = {
	propsId: 1380,
	name: "Missile Diamond-I",
	comment: "Missile Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 62,
	gemLevel: 0,
	gemKindID: 15,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	missile: "D",
	imageFileName: "Props1190"
};
items[ITEM_MISSILE_DIAMOND_2] = {
	propsId: 1381,
	name: "Missile Diamond-II",
	comment: "Missile Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 15,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	missile: "C",
	imageFileName: "Props1191"
};
items[ITEM_MISSILE_DIAMOND_3] = {
	propsId: 1382,
	name: "Missile Diamond-III",
	comment: "Missile Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 15,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	missile: "B",
	imageFileName: "Props1192"
};
items[ITEM_MISSILE_DIAMOND_4] = {
	propsId: 1383,
	name: "Missile Diamond-IV",
	comment: "Missile Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 15,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	missile: "A",
	imageFileName: "Props1193"
};
items[ITEM_MISSILE_DIAMOND_5] = {
	propsId: 1384,
	name: "Missile Diamond-V",
	comment: "Missile Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 15,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	missile: "S",
	imageFileName: "Props1194"
};
items[ITEM_TACTICAL_DIAMOND_1] = {
	propsId: 1385,
	name: "Tactical Diamond-I",
	comment: "Ship-based Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 63,
	gemLevel: 0,
	gemKindID: 16,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	carrier: "D",
	imageFileName: "Props1110"
};
items[ITEM_TACTICAL_DIAMOND_2] = {
	propsId: 1386,
	name: "Tactical Diamond-II",
	comment: "Ship-based Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 16,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	carrier: "C",
	imageFileName: "Props1111"
};
items[ITEM_TACTICAL_DIAMOND_3] = {
	propsId: 1387,
	name: "Tactical Diamond-III",
	comment: "Ship-based Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 16,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	carrier: "B",
	imageFileName: "Props1112"
};
items[ITEM_TACTICAL_DIAMOND_4] = {
	propsId: 1388,
	name: "Tactical Diamond-IV",
	comment: "Ship-based Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 16,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	carrier: "A",
	imageFileName: "Props1113"
};
items[ITEM_TACTICAL_DIAMOND_5] = {
	propsId: 1389,
	name: "Tactical Diamond-V",
	comment: "Ship-based Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 16,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	carrier: "S",
	imageFileName: "Props1114"
};
items[ITEM_GLOBAL_ASSAULT_DIAMOND_1] = {
	propsId: 1390,
	name: "Global Assault Diamond-I",
	comment: "Planet-attack Weapon Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 64,
	gemLevel: 0,
	gemKindID: 17,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	defend: "D",
	imageFileName: "Props1040"
};
items[ITEM_GLOBAL_ASSAULT_DIAMOND_2] = {
	propsId: 1391,
	name: "Global Assault Diamond-II",
	comment: "Planet-attack Weapon Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 17,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	defend: "C",
	imageFileName: "Props1041"
};
items[ITEM_GLOBAL_ASSAULT_DIAMOND_3] = {
	propsId: 1392,
	name: "Global Assault Diamond-III",
	comment: "Planet-attack Weapon Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 17,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	defend: "B",
	imageFileName: "Props1042"
};
items[ITEM_GLOBAL_ASSAULT_DIAMOND_4] = {
	propsId: 1393,
	name: "Global Assault Diamond-IV",
	comment: "Planet-attack Weapon Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 17,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	defend: "A",
	imageFileName: "Props1043"
};
items[ITEM_GLOBAL_ASSAULT_DIAMOND_5] = {
	propsId: 1394,
	name: "Global Assault Diamond-V",
	comment: "Planet-attack Weapon Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 17,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	defend: "S",
	imageFileName: "Props1044"
};
items[ITEM_FRIGATE_DIAMOND_1] = {
	propsId: 1395,
	name: "Frigate Diamond-I",
	comment: "Frigate Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 65,
	gemLevel: 0,
	gemKindID: 18,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	frigate: "D",
	imageFileName: "Props1090"
};
items[ITEM_FRIGATE_DIAMOND_2] = {
	propsId: 1396,
	name: "Frigate Diamond-II",
	comment: "Frigate Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 18,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	frigate: "C",
	imageFileName: "Props1091"
};
items[ITEM_FRIGATE_DIAMOND_3] = {
	propsId: 1397,
	name: "Frigate Diamond-III",
	comment: "Frigate Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 18,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	frigate: "B",
	imageFileName: "Props1092"
};
items[ITEM_FRIGATE_DIAMOND_4] = {
	propsId: 1398,
	name: "Frigate Diamond-IV",
	comment: "Frigate Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 18,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	frigate: "A",
	imageFileName: "Props1093"
};
items[ITEM_FRIGATE_DIAMOND_5] = {
	propsId: 1399,
	name: "Frigate Diamond-V",
	comment: "Frigate Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 18,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	frigate: "S",
	imageFileName: "Props1094"
};
items[ITEM_CRUISER_DIAMOND_1] = {
	propsId: 1400,
	name: "Cruiser Diamond-I",
	comment: "Cruiser Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 66,
	gemLevel: 0,
	gemKindID: 19,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	cruiser: "D",
	imageFileName: "Props1180"
};
items[ITEM_CRUISER_DIAMOND_2] = {
	propsId: 1401,
	name: "Cruiser Diamond-II",
	comment: "Cruiser Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 19,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	cruiser: "C",
	imageFileName: "Props1181"
};
items[ITEM_CRUISER_DIAMOND_3] = {
	propsId: 1402,
	name: "Cruiser Diamond-III",
	comment: "Cruiser Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 19,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	cruiser: "B",
	imageFileName: "Props1182"
};
items[ITEM_CRUISER_DIAMOND_4] = {
	propsId: 1403,
	name: "Cruiser Diamond-IV",
	comment: "Cruiser Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 19,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	cruiser: "A",
	imageFileName: "Props1183"
};
items[ITEM_CRUISER_DIAMOND_5] = {
	propsId: 1404,
	name: "Cruiser Diamond-V",
	comment: "Cruiser Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 19,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	cruiser: "S",
	imageFileName: "Props1184"
};
items[ITEM_BATTLESHIP_DIAMOND_1] = {
	propsId: 1405,
	name: "Battleship Diamond-I",
	comment: "Battleship Expertise will be upgraded to Level D. Higher level Expertise won't be degraded.",
	suspendID: 0,
	cash: 25,
	assortID: 3,
	orderID: 67,
	gemLevel: 0,
	gemKindID: 20,
	gemValue: "D",
	gemColor: 4,
	diamond: 1,
	battleship: "D",
	imageFileName: "Props1185"
};
items[ITEM_BATTLESHIP_DIAMOND_2] = {
	propsId: 1406,
	name: "Battleship Diamond-II",
	comment: "Battleship Expertise will be upgraded to Level C. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 20,
	gemValue: "C",
	gemColor: 4,
	diamond: 1,
	battleship: "C",
	imageFileName: "Props1186"
};
items[ITEM_BATTLESHIP_DIAMOND_3] = {
	propsId: 1407,
	name: "Battleship Diamond-III",
	comment: "Battleship Expertise will be upgraded to Level B. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 20,
	gemValue: "B",
	gemColor: 4,
	diamond: 1,
	battleship: "B",
	imageFileName: "Props1187"
};
items[ITEM_BATTLESHIP_DIAMOND_4] = {
	propsId: 1408,
	name: "Battleship Diamond-IV",
	comment: "Battleship Expertise will be upgraded to Level A. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 20,
	gemValue: "A",
	gemColor: 4,
	diamond: 1,
	battleship: "A",
	imageFileName: "Props1188"
};
items[ITEM_BATTLESHIP_DIAMOND_5] = {
	propsId: 1409,
	name: "Battleship Diamond-V",
	comment: "Battleship Expertise will be upgraded to Level S. Higher level Expertise won't be degraded.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 20,
	gemValue: "S",
	gemColor: 4,
	diamond: 1,
	battleship: "S",
	imageFileName: "Props1189"
};
items[ITEM_BURNING_TRIAD_1] = {
	propsId: 4229,
	name: "Burning Triad-I",
	comment: "Increases Attack Power by 0.7%, Double Attack rate by 0.9%, and Structure by 0.4%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 21,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 70,
	endure: 40,
	doubleHit: 90,
	broadcastFlag: 0,
	resultGem: "1;6;2",
	imageFileName: "Props4229"
};
items[ITEM_BURNING_TRIAD_2] = {
	propsId: 4230,
	name: "Burning Triad-II",
	comment: "Increases Attack Power by 1.3%, Double Attack rate by 1.7%, and Structure by 0.8%. Sockets.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 21,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 130,
	endure: 80,
	doubleHit: 170,
	broadcastFlag: 0,
	resultGem: "1;6;2",
	imageFileName: "Props4230"
};
items[ITEM_BURNING_TRIAD_3] = {
	propsId: 4231,
	name: "Burning Triad-III",
	comment: "Increases Attack Power by 2%, Double Attack rate by 2.6%, and Structure by 1.3%.ond Sockets.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 21,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 200,
	endure: 130,
	doubleHit: 260,
	broadcastFlag: 0,
	resultGem: "1;6;2",
	imageFileName: "Props4231"
};
items[ITEM_BURNING_TRIAD_4] = {
	propsId: 4232,
	name: "Burning Triad-IV",
	comment: "Increases Attack Power by 2.7%, Double Attack rate by 3.4%, and Structure by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 21,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 270,
	endure: 170,
	doubleHit: 340,
	broadcastFlag: 1,
	resultGem: "1;6;2",
	imageFileName: "Props4232"
};
items[ITEM_BURNING_TRIAD_5] = {
	propsId: 4233,
	name: "Burning Triad-V",
	comment: "Increases Attack Power by 3.3%, Double Attack rate by 4.3%, and Structure by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 21,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	assault: 330,
	endure: 220,
	doubleHit: 430,
	broadcastFlag: 1,
	resultGem: "1;6;2",
	imageFileName: "Props4233"
};
items[ITEM_GUARDIAN_TRIAD_1] = {
	propsId: 4234,
	name: "Guardian Triad-I",
	comment: "Increases Structure by 0.4%, Shields by 0.5% and Shield Regeneration Rate by 0.8%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 22,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 40,
	shield: 50,
	repairShield: 80,
	broadcastFlag: 0,
	resultGem: "2;3;7",
	imageFileName: "Props4234"
};
items[ITEM_GUARDIAN_TRIAD_2] = {
	propsId: 4235,
	name: "Guardian Triad-II",
	comment: "Increases Structure by 0.8%, Shields by 1% and Shield Regeneration Rate by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 22,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 80,
	shield: 100,
	repairShield: 150,
	broadcastFlag: 0,
	resultGem: "2;3;7",
	imageFileName: "Props4235"
};
items[ITEM_GUARDIAN_TRIAD_3] = {
	propsId: 4236,
	name: "Guardian Triad-III",
	comment: "Increases Structure by 1.3%, Shields by 1.6% and Shield Regeneration Rate by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 22,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 130,
	shield: 160,
	repairShield: 230,
	broadcastFlag: 0,
	resultGem: "2;3;7",
	imageFileName: "Props4236"
};
items[ITEM_GUARDIAN_TRIAD_4] = {
	propsId: 4237,
	name: "Guardian Triad-IV",
	comment: "Increases Structure by 1.7%, Shields by 2.1% and Shield Regeneration Rate by 3.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 22,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 170,
	shield: 210,
	repairShield: 310,
	broadcastFlag: 1,
	resultGem: "2;3;7",
	imageFileName: "Props4237"
};
items[ITEM_GUARDIAN_TRIAD_5] = {
	propsId: 4238,
	name: "Guardian Triad-V",
	comment: "Increases Structure by 2.2%, Shields by 2.7% and Shield Regeneration Rate by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 22,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	endure: 220,
	shield: 270,
	repairShield: 380,
	broadcastFlag: 1,
	resultGem: "2;3;7",
	imageFileName: "Props4238"
};
items[ITEM_GIANT_TRIAD_1] = {
	propsId: 4239,
	name: "Giant Triad-I",
	comment: "Increases Critical Strike rate by 0.7%, Critical Strike damage by 2.2%, and Double Attack rate by 0.9%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 23,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 220,
	blast: 70,
	doubleHit: 90,
	broadcastFlag: 0,
	resultGem: "5;4;6",
	imageFileName: "Props4239"
};
items[ITEM_GIANT_TRIAD_2] = {
	propsId: 4240,
	name: "Giant Triad-II",
	comment: "Increases Critical Strike rate by 1.3%, Critical Strike damage by 4.5%, and Double Attack rate by 1.7%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 23,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 450,
	blast: 130,
	doubleHit: 170,
	broadcastFlag: 0,
	resultGem: "5;4;6",
	imageFileName: "Props4240"
};
items[ITEM_GIANT_TRIAD_3] = {
	propsId: 4241,
	name: "Giant Triad-III",
	comment: "Increases Critical Strike rate by 2%, Critical Strike damage by 6.7%, and Double Attack rate by 2.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 23,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 670,
	blast: 200,
	doubleHit: 260,
	broadcastFlag: 0,
	resultGem: "5;4;6",
	imageFileName: "Props4241"
};
items[ITEM_GIANT_TRIAD_4] = {
	propsId: 4242,
	name: "Giant Triad-IV",
	comment: "Increases Critical Strike rate by 2.7%, Critical Strike damage by 9%, and Double Attack rate by 3.4%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 23,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 900,
	blast: 270,
	doubleHit: 340,
	broadcastFlag: 1,
	resultGem: "5;4;6",
	imageFileName: "Props4242"
};
items[ITEM_GIANT_TRIAD_5] = {
	propsId: 4243,
	name: "Giant Triad-V",
	comment: "Increases Critical Strike rate by 3.3%, Critical Strike damage by 11.1%, and Double Attack rate by 4.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 23,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blastHurt: 1110,
	blast: 330,
	doubleHit: 430,
	broadcastFlag: 1,
	resultGem: "5;4;6",
	imageFileName: "Props4243"
};
items[ITEM_QUADRA_ACCURACY_RUBY_1] = {
	propsId: 4244,
	name: "Quadra Accuracy Ruby-I",
	comment: "Increases Accuracy by 13, Attack Power by 0.7%, Double Attack rate by 0.9%, and Structure by 0.4%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 24,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 13,
	assault: 70,
	endure: 40,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1200,
	imageFileName: "Props4244"
};
items[ITEM_QUADRA_ACCURACY_RUBY_2] = {
	propsId: 4245,
	name: "Quadra Accuracy Ruby-II",
	comment: "Increases Accuracy by 26, Attack Power by 1.3%, Double Attack rate by 1.7%, and Structure by 0.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 24,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 26,
	assault: 130,
	endure: 80,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1200,
	imageFileName: "Props4245"
};
items[ITEM_QUADRA_ACCURACY_RUBY_3] = {
	propsId: 4246,
	name: "Quadra Accuracy Ruby-III",
	comment: "Increases Accuracy by 39, Attack Power by 2%, Double Attack rate by 2.6%, and Structure by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 24,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 39,
	assault: 200,
	endure: 130,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1200,
	imageFileName: "Props4246"
};
items[ITEM_QUADRA_ACCURACY_RUBY_4] = {
	propsId: 4247,
	name: "Quadra Accuracy Ruby-IV",
	comment: "Increases Accuracy by 52, Attack Power by 2.7%, Double Attack rate by 3.4%, and Structure by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 24,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 52,
	assault: 270,
	endure: 170,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1200,
	imageFileName: "Props4247"
};
items[ITEM_QUADRA_ACCURACY_RUBY_5] = {
	propsId: 4248,
	name: "Quadra Accuracy Ruby-V",
	comment: "Increases Accuracy by 65, Attack Power by 3.3%, Double Attack rate by 4.3%, and Structure by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 24,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	aim: 65,
	assault: 330,
	endure: 220,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1200,
	imageFileName: "Props4248"
};
items[ITEM_QUADRA_DODGE_RUBY_1] = {
	propsId: 4249,
	name: "Quadra Dodge Ruby-I",
	comment: "Increases Dodge by 5, Attack Power by 0.7%, Double Attack rate by 0.9%, and Structure by 0.4%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 25,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 5,
	assault: 70,
	endure: 40,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1215,
	imageFileName: "Props4249"
};
items[ITEM_QUADRA_DODGE_RUBY_2] = {
	propsId: 4250,
	name: "Quadra Dodge Ruby-II",
	comment: "Increases Dodge by 10, Attack Power by 1.3%, Double Attack rate by 1.7%, and Structure by 0.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 25,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 10,
	assault: 130,
	endure: 80,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1215,
	imageFileName: "Props4250"
};
items[ITEM_QUADRA_DODGE_RUBY_3] = {
	propsId: 4251,
	name: "Quadra Dodge Ruby-III",
	comment: "Increases Dodge by 15, Attack Power by 2%, Double Attack rate by 2.6%, and Structure by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 25,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 15,
	assault: 200,
	endure: 130,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1215,
	imageFileName: "Props4251"
};
items[ITEM_QUADRA_DODGE_RUBY_4] = {
	propsId: 4252,
	name: "Quadra Dodge Ruby-IV",
	comment: "Increases Dodge by 20, Attack Power by 2.7%, Double Attack rate by 3.4%, and Structure by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 25,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 20,
	assault: 270,
	endure: 170,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1215,
	imageFileName: "Props4252"
};
items[ITEM_QUADRA_DODGE_RUBY_5] = {
	propsId: 4253,
	name: "Quadra Dodge Ruby-V",
	comment: "Increases Dodge by 25, Attack Power by 3.3%, Double Attack rate by 4.3%, and Structure by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 25,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	blench: 25,
	assault: 330,
	endure: 220,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1215,
	imageFileName: "Props4253"
};
items[ITEM_QUADRA_SPEED_RUBY_1] = {
	propsId: 4254,
	name: "Quadra Speed Ruby-I",
	comment: "Increases Speed by 9, Attack Power by 0.7%, Double Attack rate by 0.9%, and Structure by 0.4%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 26,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 9,
	assault: 70,
	endure: 40,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1245,
	imageFileName: "Props4254"
};
items[ITEM_QUADRA_SPEED_RUBY_2] = {
	propsId: 4255,
	name: "Quadra Speed Ruby-II",
	comment: "Increases Speed by 18, Attack Power by 1.3%, Double Attack rate by 1.7%, and Structure by 0.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 26,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 18,
	assault: 130,
	endure: 80,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1245,
	imageFileName: "Props4255"
};
items[ITEM_QUADRA_SPEED_RUBY_3] = {
	propsId: 4256,
	name: "Quadra Speed Ruby-III",
	comment: "Increases Speed by 27, Attack Power by 2%, Double Attack rate by 2.6%, and Structure by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 26,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 27,
	assault: 200,
	endure: 130,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1245,
	imageFileName: "Props4256"
};
items[ITEM_QUADRA_SPEED_RUBY_4] = {
	propsId: 4257,
	name: "Quadra Speed Ruby-IV",
	comment: "Increases Speed by 36, Attack Power by 2.7%, Double Attack rate by 3.4%, and Structure by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 26,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 36,
	assault: 270,
	endure: 170,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1245,
	imageFileName: "Props4257"
};
items[ITEM_QUADRA_SPEED_RUBY_5] = {
	propsId: 4258,
	name: "Quadra Speed Ruby-V",
	comment: "Increases Speed by 45, Attack Power by 3.3%, Double Attack rate by 4.3%, and Structure by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 26,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	priority: 45,
	assault: 330,
	endure: 220,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1245,
	imageFileName: "Props4258"
};
items[ITEM_QUADRA_ELECTRON_RUBY_1] = {
	propsId: 4259,
	name: "Quadra Electron Ruby-I",
	comment: "Increases Electron by 9, Attack Power by 0.7%, Double Attack rate by 0.9%, and Structure by 0.4%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 9,
	assault: 70,
	endure: 40,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1230,
	imageFileName: "Props4259"
};
items[ITEM_QUADRA_ELECTRON_RUBY_2] = {
	propsId: 4260,
	name: "Quadra Electron Ruby-II",
	comment: "Increases Electron by 18 Attack Power by 1.3%, Double Attack rate by 1.7%, and Structure by 0.8%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 18,
	assault: 130,
	endure: 80,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1230,
	imageFileName: "Props4260"
};
items[ITEM_QUADRA_ELECTRON_RUBY_3] = {
	propsId: 4261,
	name: "Quadra Electron Ruby-III",
	comment: "Increases Electron by 27, Attack Power by 2%, Double Attack rate by 2.6%, and Structure by 1.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 27,
	assault: 200,
	endure: 130,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1230,
	imageFileName: "Props4261"
};
items[ITEM_QUADRA_ELECTRON_RUBY_4] = {
	propsId: 4262,
	name: "Quadra Electron Ruby-IV",
	comment: "Increases Electron by 36, Attack Power by 2.7%, Double Attack rate by 3.4%, and Structure by 1.7%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 36,
	assault: 270,
	endure: 170,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1230,
	imageFileName: "Props4262"
};
items[ITEM_QUADRA_ELECTRON_RUBY_5] = {
	propsId: 4263,
	name: "Quadra Electron Ruby-V",
	comment: "Increases Electron by 45, Attack Power by 3.3%, Double Attack rate by 4.3%, and Structure by 2.2%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 27,
	gemColor: 1,
	red: 1,
	//diamond: 1,
	electron: 45,
	assault: 330,
	endure: 220,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1230,
	imageFileName: "Props4263"
};
items[ITEM_QUADRA_ACCURACY_SAPPHIRE_1] = {
	propsId: 4264,
	name: "Quadra Accuracy Sapphire-I",
	comment: "Increases Accuracy by 9, Structure by 0.4%, Shields by 0.5%, and Shield Regeneration Rate by 0.8%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 28,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 9,
	endure: 40,
	shield: 50,
	repairShield: 80,
	broadcastFlag: 0,
	gem1ID: 1205,
	imageFileName: "Props4264"
};
items[ITEM_QUADRA_ACCURACY_SAPPHIRE_2] = {
	propsId: 4265,
	name: "Quadra Accuracy Sapphire-II",
	comment: "Increases Accuracy by 18, Structure by 0.8%, Shields by 1%, and Shield Regeneration Rate by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 28,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 18,
	endure: 80,
	shield: 100,
	repairShield: 150,
	broadcastFlag: 0,
	gem1ID: 1205,
	imageFileName: "Props4265"
};
items[ITEM_QUADRA_ACCURACY_SAPPHIRE_3] = {
	propsId: 4266,
	name: "Quadra Accuracy Sapphire-III",
	comment: "Increases Accuracy by 27, Structure by 1.3%, Shields by 1.6%, and Shield Regeneration Rate by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 28,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 27,
	endure: 130,
	shield: 160,
	repairShield: 230,
	broadcastFlag: 0,
	gem1ID: 1205,
	imageFileName: "Props4266"
};
items[ITEM_QUADRA_ACCURACY_SAPPHIRE_4] = {
	propsId: 4267,
	name: "Quadra Accuracy Sapphire-IV",
	comment: "Increases Accuracy by 36, Structure by 1.7%, Shields by 2.1%, and Shield Regeneration Rate by 3.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 28,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 36,
	endure: 170,
	shield: 210,
	repairShield: 310,
	broadcastFlag: 1,
	gem1ID: 1205,
	imageFileName: "Props4267"
};
items[ITEM_QUADRA_ACCURACY_SAPPHIRE_5] = {
	propsId: 4268,
	name: "Quadra Accuracy Sapphire-V",
	comment: "Increases Accuracy by 45, Structure by 2.2%, Shields by 2.7%, and Shield Regeneration Rate by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 28,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	aim: 45,
	endure: 220,
	shield: 270,
	repairShield: 380,
	broadcastFlag: 1,
	gem1ID: 1205,
	imageFileName: "Props4268"
};
items[ITEM_QUADRA_DODGE_SAPPHIRE_1] = {
	propsId: 4269,
	name: "Quadra Dodge Sapphire-I",
	comment: "Increases Dodge by 13, Structure by 0.4%, Shields by 0.5%, and Shield Regeneration Rate by 0.8%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 29,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 13,
	endure: 40,
	shield: 50,
	repairShield: 80,
	broadcastFlag: 0,
	gem1ID: 1220,
	imageFileName: "Props4269"
};
items[ITEM_QUADRA_DODGE_SAPPHIRE_2] = {
	propsId: 4270,
	name: "Quadra Dodge Sapphire-II",
	comment: "Increases Dodge by 26, Structure by 0.8%, Shields by 1%, and Shield Regeneration Rate by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 29,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 26,
	endure: 80,
	shield: 100,
	repairShield: 150,
	broadcastFlag: 0,
	gem1ID: 1220,
	imageFileName: "Props4270"
};
items[ITEM_QUADRA_DODGE_SAPPHIRE_3] = {
	propsId: 4271,
	name: "Quadra Dodge Sapphire-III",
	comment: "Increases Dodge by 39, Structure by 1.4%, Shields by 1.6%, and Shield Regeneration Rate by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 29,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 39,
	endure: 130,
	shield: 160,
	repairShield: 230,
	broadcastFlag: 0,
	gem1ID: 1220,
	imageFileName: "Props4271"
};
items[ITEM_QUADRA_DODGE_SAPPHIRE_4] = {
	propsId: 4272,
	name: "Quadra Dodge Sapphire-IV",
	comment: "Increases Dodge by 52, Structure by 1.7%, Shields by 2.1%, and Shield Regeneration Rate by 3.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 29,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 52,
	endure: 170,
	shield: 210,
	repairShield: 310,
	broadcastFlag: 1,
	gem1ID: 1220,
	imageFileName: "Props4272"
};
items[ITEM_QUADRA_DODGE_SAPPHIRE_5] = {
	propsId: 4273,
	name: "Quadra Dodge Sapphire-V",
	comment: "Increases Dodge by 65, Structure by 2.2%, Shields by 2.7%, and Shield Regeneration Rate by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 29,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	blench: 65,
	endure: 220,
	shield: 270,
	repairShield: 380,
	broadcastFlag: 1,
	gem1ID: 1220,
	imageFileName: "Props4273"
};
items[ITEM_QUADRA_SPEED_SAPPHIRE_1] = {
	propsId: 4274,
	name: "Quadra Speed Sapphire-I",
	comment: "Increases Speed by 5, Structure by 0.4%, Shields by 0.5%, and Shield Regeneration Rate by 0.8%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 30,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 5,
	endure: 40,
	shield: 50,
	repairShield: 80,
	broadcastFlag: 0,
	gem1ID: 1250,
	imageFileName: "Props4274"
};
items[ITEM_QUADRA_SPEED_SAPPHIRE_2] = {
	propsId: 4275,
	name: "Quadra Speed Sapphire-II",
	comment: "Increases Speed by 10, Structure by 0.8%, Shields by 1%, and Shield Regeneration Rate by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 30,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 10,
	endure: 80,
	shield: 100,
	repairShield: 150,
	broadcastFlag: 0,
	gem1ID: 1250,
	imageFileName: "Props4275"
};
items[ITEM_QUADRA_SPEED_SAPPHIRE_3] = {
	propsId: 4276,
	name: "Quadra Speed Sapphire-III",
	comment: "Increases Speed by 15, Structure by 1.3%, Shields by 1.6%, and Shield Regeneration Rate by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 30,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 15,
	endure: 130,
	shield: 160,
	repairShield: 230,
	broadcastFlag: 0,
	gem1ID: 1250,
	imageFileName: "Props4276"
};
items[ITEM_QUADRA_SPEED_SAPPHIRE_4] = {
	propsId: 4277,
	name: "Quadra Speed Sapphire-IV",
	comment: "Increases Speed by 20, Structure by 1.7%, Shields by 2.1%, and Shield Regeneration Rate by 3.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 30,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 20,
	endure: 170,
	shield: 210,
	repairShield: 310,
	broadcastFlag: 1,
	gem1ID: 1250,
	imageFileName: "Props4277"
};
items[ITEM_QUADRA_SPEED_SAPPHIRE_5] = {
	propsId: 4278,
	name: "Quadra Speed Sapphire-V",
	comment: "Increases Speed by 25, Structure by 2.2%, Shields by 2.7%, and Shield Regeneration Rate by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 30,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	priority: 25,
	endure: 220,
	shield: 270,
	repairShield: 380,
	broadcastFlag: 1,
	gem1ID: 1250,
	imageFileName: "Props4278"
};
items[ITEM_QUADRA_ELECTRON_SAPPHIRE_1] = {
	propsId: 4279,
	name: "Quadra Electron Sapphire-I",
	comment: "Increases Electron by 5, Structure by 0.4%, Shields by 0.5%, and Shield Regeneration Rate by 0.8%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 31,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 5,
	endure: 40,
	shield: 50,
	repairShield: 80,
	broadcastFlag: 0,
	gem1ID: 1235,
	imageFileName: "Props4279"
};
items[ITEM_QUADRA_ELECTRON_SAPPHIRE_2] = {
	propsId: 4280,
	name: "Quadra Electron Sapphire-II",
	comment: "Increases Electron by 10, Structure by 0.8%, Shields by 1%, and Shield Regeneration Rate by 1.5%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 31,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 10,
	endure: 80,
	shield: 100,
	repairShield: 150,
	broadcastFlag: 0,
	gem1ID: 1235,
	imageFileName: "Props4280"
};
items[ITEM_QUADRA_ELECTRON_SAPPHIRE_3] = {
	propsId: 4281,
	name: "Quadra Electron Sapphire-III",
	comment: "Increases Electron by 15, Structure by 1.3%, Shields by 1.6%, and Shield Regeneration Rate by 2.3%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 31,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 15,
	endure: 130,
	shield: 160,
	repairShield: 230,
	broadcastFlag: 0,
	gem1ID: 1235,
	imageFileName: "Props4281"
};
items[ITEM_QUADRA_ELECTRON_SAPPHIRE_4] = {
	propsId: 4282,
	name: "Quadra Electron Sapphire-IV",
	comment: "Increases Electron by 20, Structure by 1.7%, Shields by 2.1%, and Shield Regeneration Rate by 3.1%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 31,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 20,
	endure: 170,
	shield: 210,
	repairShield: 310,
	broadcastFlag: 1,
	gem1ID: 1235,
	imageFileName: "Props4282"
};
items[ITEM_QUADRA_ELECTRON_SAPPHIRE_5] = {
	propsId: 4283,
	name: "Quadra Electron Sapphire-V",
	comment: "Increases Electron by 25, Structure by 2.2%, Shields by 2.7%, and Shield Regeneration Rate by 3.8%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 31,
	gemColor: 2,
	blue: 1,
	//diamond: 1,
	electron: 25,
	endure: 220,
	shield: 270,
	repairShield: 380,
	broadcastFlag: 1,
	gem1ID: 1235,
	imageFileName: "Props4283"
};
items[ITEM_QUADRA_ACCURACY_EMERALD_1] = {
	propsId: 4284,
	name: "Quadra Accuracy Emerald-I",
	comment: "Increases Accuracy by 5, Critical Strike rate by 0.7%, Critical Strike damage by 2.2%, and Double Attack rate by 0.9%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 32,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 5,
	blastHurt: 220,
	blast: 70,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1210,
	imageFileName: "Props4284"
};
items[ITEM_QUADRA_ACCURACY_EMERALD_2] = {
	propsId: 4285,
	name: "Quadra Accuracy Emerald-II",
	comment: "Increases Accuracy by 10, Critical Strike rate by 1.3%, Critical Strike damage by 4.5%, and Double Attack rate by 1.7%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 32,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 10,
	blastHurt: 450,
	blast: 130,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1210,
	imageFileName: "Props4285"
};
items[ITEM_QUADRA_ACCURACY_EMERALD_3] = {
	propsId: 4286,
	name: "Quadra Accuracy Emerald-III",
	comment: "Increases Accuracy by 15, Critical Strike rate by 2%, Critical Strike damage by 6.7%, and Double Attack rate by 2.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 32,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 15,
	blastHurt: 670,
	blast: 200,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1210,
	imageFileName: "Props4286"
};
items[ITEM_QUADRA_ACCURACY_EMERALD_4] = {
	propsId: 4287,
	name: "Quadra Accuracy Emerald-IV",
	comment: "Increases Accuracy by 20, Critical Strike rate by 2.7%, Critical Strike damage by 9%, and Double Attack rate by 3.4%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 32,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 20,
	blastHurt: 900,
	blast: 270,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1210,
	imageFileName: "Props4287"
};
items[ITEM_QUADRA_ACCURACY_EMERALD_5] = {
	propsId: 4288,
	name: "Quadra Accuracy Emerald-V",
	comment: "Increases Accuracy by 25, Critical Strike rate by 3.3%, Critical Strike damage by 11.1%, and Double Attack rate by 4.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 32,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	aim: 25,
	blastHurt: 1110,
	blast: 330,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1210,
	imageFileName: "Props4288"
};
items[ITEM_QUADRA_DODGE_EMERALD_1] = {
	propsId: 4289,
	name: "Quadra Dodge Emerald-I",
	comment: "Increases Dodge by 9, Critical Strike rate by 0.7%, Critical Strike damage by 2.2%, and Double Attack rate by 0.9%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 33,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 9,
	blastHurt: 220,
	blast: 70,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1225,
	imageFileName: "Props4289"
};
items[ITEM_QUADRA_DODGE_EMERALD_2] = {
	propsId: 4290,
	name: "Quadra Dodge Emerald-II",
	comment: "Increases Dodge by 18, Critical Strike rate by 1.3%, Critical Strike damage by 4.5%, and Double Attack rate by 1.7%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 33,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 18,
	blastHurt: 450,
	blast: 130,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1225,
	imageFileName: "Props4290"
};
items[ITEM_QUADRA_DODGE_EMERALD_3] = {
	propsId: 4291,
	name: "Quadra Dodge Emerald-III",
	comment: "Increases Dodge by 27, Critical Strike rate by 2%, Critical Strike damage by 6.7%, and Double Attack rate by 2.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 33,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 27,
	blastHurt: 670,
	blast: 200,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1225,
	imageFileName: "Props4291"
};
items[ITEM_QUADRA_DODGE_EMERALD_4] = {
	propsId: 4292,
	name: "Quadra Dodge Emerald-IV",
	comment: "Increases Dodge by 36, Critical Strike rate by 2.7%, Critical Strike damage by 9%, and Double Attack rate by 3.4%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 33,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 36,
	blastHurt: 900,
	blast: 270,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1225,
	imageFileName: "Props4292"
};
items[ITEM_QUADRA_DODGE_EMERALD_5] = {
	propsId: 4293,
	name: "Quadra Dodge Emerald-V",
	comment: "Increases Dodge by 45, Critical Strike rate by 3.3%, Critical Strike damage by 11.1%, and Double Attack rate by 4.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 33,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	blench: 45,
	blastHurt: 1110,
	blast: 330,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1225,
	imageFileName: "Props4293"
};
items[ITEM_QUADRA_SPEED_EMERALD_1] = {
	propsId: 4294,
	name: "Quadra Speed Emerald-I",
	comment: "Increases Speed by 13, Critical Strike rate by 0.7%, Critical Strike damage by 2.2%, and Double Attack rate by 0.9%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 34,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 13,
	blastHurt: 220,
	blast: 70,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1255,
	imageFileName: "Props4294"
};
items[ITEM_QUADRA_SPEED_EMERALD_2] = {
	propsId: 4295,
	name: "Quadra Speed Emerald-II",
	comment: "Increases Speed by 26, Critical Strike rate by 1.3%, Critical Strike damage by 4.5%, and Double Attack rate by 1.7%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 34,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 26,
	blastHurt: 450,
	blast: 130,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1255,
	imageFileName: "Props4295"
};
items[ITEM_QUADRA_SPEED_EMERALD_3] = {
	propsId: 4296,
	name: "Quadra Speed Emerald-III",
	comment: "Increases Speed by 39, Critical Strike rate by 2%, Critical Strike damage by 6.7%, and Double Attack rate by 2.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 34,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 39,
	blastHurt: 670,
	blast: 200,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1255,
	imageFileName: "Props4296"
};
items[ITEM_QUADRA_SPEED_EMERALD_4] = {
	propsId: 4297,
	name: "Quadra Speed Emerald-IV",
	comment: "Increases Speed by 52, Critical Strike rate by 2.7%, Critical Strike damage by 9%, and Double Attack rate by 3.4%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 34,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 52,
	blastHurt: 900,
	blast: 270,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1255,
	imageFileName: "Props4297"
};
items[ITEM_QUADRA_SPEED_EMERALD_5] = {
	propsId: 4298,
	name: "Quadra Speed Emerald-V",
	comment: "Increases Speed by 65, Critical Strike rate by 3.3%, Critical Strike damage by 11.1%, and Double Attack rate by 4.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 34,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	priority: 65,
	blastHurt: 1110,
	blast: 330,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1255,
	imageFileName: "Props4298"
};
items[ITEM_QUADRA_ELECTRON_EMERALD_1] = {
	propsId: 4299,
	name: "Quadra Electron Emerald-I",
	comment: "Increases Electron by 13, Critical Strike rate by 0.7%, Critical Strike damage by 2.2%, and Double Attack rate by 0.9%.",
	suspendID: 0,
	assortID: 3,
	gemLevel: 0,
	gemKindID: 35,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 13,
	blastHurt: 220,
	blast: 70,
	doubleHit: 90,
	broadcastFlag: 0,
	gem1ID: 1240,
	imageFileName: "Props4299"
};
items[ITEM_QUADRA_ELECTRON_EMERALD_2] = {
	propsId: 4300,
	name: "Quadra Electron Emerald-II",
	comment: "Increases Electron by 26, Critical Strike rate by 1.3%, Critical Strike damage by 4.5%, and Double Attack rate by 1.7%.",
	suspendID: 0,
	gemLevel: 1,
	gemKindID: 35,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 26,
	blastHurt: 450,
	blast: 130,
	doubleHit: 170,
	broadcastFlag: 0,
	gem1ID: 1240,
	imageFileName: "Props4300"
};
items[ITEM_QUADRA_ELECTRON_EMERALD_3] = {
	propsId: 4301,
	name: "Quadra Electron Emerald-III",
	comment: "Increases Electron by 39, Critical Strike rate by 2%, Critical Strike damage by 6.7%, and Double Attack rate by 2.6%.",
	suspendID: 0,
	gemLevel: 2,
	gemKindID: 35,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 39,
	blastHurt: 670,
	blast: 200,
	doubleHit: 260,
	broadcastFlag: 0,
	gem1ID: 1240,
	imageFileName: "Props4301"
};
items[ITEM_QUADRA_ELECTRON_EMERALD_4] = {
	propsId: 4302,
	name: "Quadra Electron Emerald-IV",
	comment: "Increases Electron by 52, Critical Strike rate by 2.7%, Critical Strike damage by 9%, and Double Attack rate by 3.4%.",
	suspendID: 0,
	gemLevel: 3,
	gemKindID: 35,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 52,
	blastHurt: 900,
	blast: 270,
	doubleHit: 340,
	broadcastFlag: 1,
	gem1ID: 1240,
	imageFileName: "Props4302"
};
items[ITEM_QUADRA_ELECTRON_EMERALD_5] = {
	propsId: 4303,
	name: "Quadra Electron Emerald-V",
	comment: "Increases Electron by 65, Critical Strike rate by 3.3%, Critical Strike damage by 11.1%, and Double Attack rate by 4.3%.",
	suspendID: 0,
	gemLevel: 4,
	gemKindID: 35,
	gemColor: 3,
	green: 1,
	//diamond: 1,
	electron: 65,
	blastHurt: 1110,
	blast: 330,
	doubleHit: 430,
	broadcastFlag: 1,
	gem1ID: 1240,
	imageFileName: "Props4303"
};
/*
     FILE ARCHIVED ON 20:00:03 Nov 16, 2018 AND RETRIEVED FROM THE
     INTERNET ARCHIVE ON 08:26:32 Jul 24, 2019.
     JAVASCRIPT APPENDED BY WAYBACK MACHINE, COPYRIGHT INTERNET ARCHIVE.

     ALL OTHER CONTENT MAY ALSO BE PROTECTED BY COPYRIGHT (17 U.S.C.
     SECTION 108(a)(3)).
*/
/*
playback timings (ms):
  LoadShardBlock: 43.496 (3)
  esindex: 0.025
  captures_list: 58.458
  CDXLines.iter: 10.955 (3)
  PetaboxLoader3.datanode: 65.062 (5)
  exclusion.robots: 0.154
  exclusion.robots.policy: 0.143
  RedisCDXSource: 0.845
  PetaboxLoader3.resolve: 112.388
  load_resource: 187.443
*/